### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by TerryYiDa** [yueruchen/EnlightenGAN#1]
Thank you for your excellent work， I have some questions:
1. Is the pre-training model open source?
2. model block order is CONV->leakyrelu-> bn, why not is conv-bn-leakyrelu?

**Comment by laomaup** [comment]
thank you for sharing, i have a problem.
ModuleNotFoundError: No module named 'psnr'    when running test.py.

**Comment by yueruchen** [comment]
I will open source other guideline soon, please wait a few days.

**Comment by yueruchen** [comment]
@TerryYiDa @laomaup 
Hi, I have uploaded the specific command. Please contact me if you have other questions.

**Comment by UtopiaHu** [comment]
@yueruchen Thank you for your work. I couldn't find the requirements.txt file.

**Comment by yueruchen** [comment]
@UtopiaHu 
Sorry, I add it now.

**Comment by laomaup** [comment]
i am runningTesting process,  python scipts/script.py --predict
this is the problem:
CustomDatasetDataLoader
Traceback (most recent call last):
  File "predict.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File "/data/mypycode/EnlightenGAN-master/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/data/mypycode/EnlightenGAN-master/data/custom_dataset_data_loader.py", line 39, in initialize
    self.dataset = CreateDataset(opt)
  File "/data/mypycode/EnlightenGAN-master/data/custom_dataset_data_loader.py", line 11, in CreateDataset
    from data.unaligned_dataset import UnalignedDataset
  File "/data/mypycode/EnlightenGAN-master/data/unaligned_dataset.py", line 4, in <module>
    import torchvision.transforms as transforms
  File "/home/xianjin/.conda/envs/allpose/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/xianjin/.conda/envs/allpose/lib/python3.6/site-packages/torchvision/models/__init__.py", line 10, in <module>
    from . import segmentation
  File "/home/xianjin/.conda/envs/allpose/lib/python3.6/site-packages/torchvision/models/segmentation/__init__.py", line 1, in <module>
    from .segmentation import *
  File "/home/xianjin/.conda/envs/allpose/lib/python3.6/site-packages/torchvision/models/segmentation/segmentation.py", line 1, in <module>
    from .._utils import IntermediateLayerGetter
  File "/home/xianjin/.conda/envs/allpose/lib/python3.6/site-packages/torchvision/models/_utils.py", line 7, in <module>
    class IntermediateLayerGetter(nn.ModuleDict):
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'


Can you provide a more detailed file to tell us how to use it?  thank you

**Comment by laomaup** [comment]
Hi, i have a new problem when i try to train.
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
single
Traceback (most recent call last):
  File "predict.py", line 18, in <module>
    model = create_model(opt)
  File "/data/disk2/EnlightenGAN-master/models/models.py", line 36, in create_model
    model.initialize(opt)
  File "/data/disk2/EnlightenGAN-master/models/single_model.py", line 72, in initialize
    self.load_network(self.netG_A, 'G_A', which_epoch)
  File "/data/disk2/EnlightenGAN-master/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/xianjin/anaconda3/envs/enlighten/lib/python3.6/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/enlightening/200_net_G_A.pth'

where can i find checkpoints and the files.

**Comment by yueruchen** [comment]
@laomaup This is the pretrained model, you should first train the model and get it.
I will upload the pretrained model soon.

**Comment by yueruchen** [comment]
@TerryYiDa @laomaup @UtopiaHu 
I've uploaded the pre-trained model and environment requirement, follow the guideline you should get the expected results. Feel free to contact me if you have other questions.
