### ISSUE TITLE
what is lib.nn?

### ISSUE THREAD

**Issue by Theodoric008** [yueruchen/EnlightenGAN#3]
from lib.nn import SynchronizedBatchNorm2d as SynBN2d

**Comment by muyi6** [comment]
I met the same problem,as follows
Traceback (most recent call last):
  File "predict.py", line 17, in <module>
    model = create_model(opt)
  File "/opt/Github/EnlightenGAN/models/models.py", line 7, in create_model
    from .cycle_gan_model import CycleGANModel
  File "/opt/Github/EnlightenGAN/models/cycle_gan_model.py", line 13, in <module>
    from . import networks
  File "/opt/Github/EnlightenGAN/models/networks.py", line 12, in <module>
    from lib.nn import SynchronizedBatchNorm2d as SynBN2d
ModuleNotFoundError: No module named 'lib.nn'

**Comment by yueruchen** [comment]
fixed, check the latest version

**Comment by Mayur28** [comment]
I've followed the instructions specified in the readme file,though I'm not sure why am I getting a similar error as above. When I execute the "python scripts/script.py --train", I get the following error:

Traceback (most recent call last):
  File "train.py", line 19, in <module>
    model = create_model(opt)
  File "/home/alpha/Downloads/EnlightenGAN-master/models/models.py", line 20, in create_model
    from .single_model import SingleModel
  File "/home/alpha/Downloads/EnlightenGAN-master/models/single_model.py", line 15, in <module>
    from . import networks
  File "/home/alpha/Downloads/EnlightenGAN-master/models/networks.py", line 11, in <module>
    from lib.nn import SynchronizedBatchNorm2d as SynBN2d
ImportError: No module named lib.nn

Any help will be highly appreciated.
