### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils.serialization'

### ISSUE THREAD

**Issue by muyi6** [yueruchen/EnlightenGAN#7]
Hello,i'm trying to run the train.py,it always gets a runtime error,i think it's the problem of torch version,what‘s your torch version？
Another，when i replace the ’load_lua‘ with ’torchfile.load‘ in the network.py,I got the following problem：can you show me how to handle？
Thank you

Traceback (most recent call last):
  File "train.py", line 31, in <module>
    model.optimize_parameters(epoch)
  File "/opt/Github/EnlightenGAN/models/cycle_gan_model.py", line 252, in optimize_parameters
    self.backward_G(epoch)
  File "/opt/Github/EnlightenGAN/models/cycle_gan_model.py", line 199, in backward_G
    pred_fake = self.netD_A.forward(self.fake_B)
  File "/opt/Github/EnlightenGAN/models/networks.py", line 497, in forward
    return self.model(input)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not tuple

**Comment by yueruchen** [comment]
Sorry, I've updated requirement.txt file. Please see the environment details.

**Comment by mrgloom** [comment]
Why this VGG16 specific version is used?
https://github.com/yueruchen/EnlightenGAN/blob/0defa50fdce043450d132f851009efe87d2e650e/util/util.py#L121

pytorch have vgg16 model in model zoo
https://pytorch.org/docs/stable/torchvision/models.html

**Comment by yueruchen** [comment]
@mrgloom 
I think both models will work well.
